version: '2'
services:
  db:
    image: mysql:5.7
    container_name: php.mysqla
    env_file:
      - ./docker_env_mysql/env
    ports:
      - "850:3306"
    volumes:
      - ./docker_env_mysql/data:/var/lib/mysql

  weba:
    build: .
    ports:
      - "80:80"
    volumes:
      - ../:/var/www/html
    links:
      - db
    depends_on:
      - db

    container_name: webd

