version: '2'
services:
  db:
    image: mysql:5.7
    container_name: php.mysql
    env_file:
      - ./docker_env_mysql/env
    ports:
      - "850:3306"
    volumes:
      - ./docker_env_mysql/database.sql:/docker-entrypoint-initdb.d/initial.sql
      - ./docker_env_mysql/data:/var/lib/mysql

  web1:
    build: .
    ports:
      - "80:80"
    volumes:
      - ../:/var/www/html
    links:
      - db
    depends_on:
      - db

    container_name: web1

